### ISSUE TITLE
スマホのGoogle Mapアプリで地図を開けるようにしたい

### ISSUE THREAD

**Issue by ukstudio** [ukstudio/fcrockstar.com#22]

**Comment by mashiro** [comment]
今気づいたけど左上の白いボックスの Google Map で開くをクリックするとアプリで開いてくれるみたい

**Comment by ukstudio** [comment]
おぁ、ほんとだ。 androidでしか見てないけど、iPhoneもそんな感じなのかな。iPhoneのgoogle mapアプリってどうなってんだっけ。

**Comment by mashiro** [comment]
手元にあった iPhone4 で試してみたら Safari でひらいた

**Comment by ukstudio** [comment]
んじゃ、fixでいいか。
